# Generated by Django 4.2.11 on 2024-03-28 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_category_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('resume', models.CharField(max_length=500)),
                ('sumary', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numbers_of_pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=100, unique=True)),
                ('publication_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.category')),
            ],
        ),
    ]
